#Embedded TOMCAT Settings
server:
  port: 8083

# ===============================
# = DATA SOURCE DB2
# ===============================
#spring:
#  datasource:
#    url: 
#    username: 
#    password: 
#    driver-class-name: com.ibm.db2.jcc.DB2Driver
# ===============================
# = JPA / HIBERNATE
# ===============================
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.DB2Dialect 
# =================================
api:
  url : https://api.stakdek.de/api/qr/gen?data=


